# Generated by Django 5.2.8 on 2025-12-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='unique_user_contest'),
        ),
    ]
