# Generated by Django 5.2.8 on 2025-12-04 21:37

import django.db.models.deletion
import quizapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_contest_id_alter_contestant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='code',
            field=models.CharField(default=quizapp.models.generate_contest_code, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
