# Generated by Django 5.2.8 on 2025-12-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_alter_contest_code_alter_contest_created_by'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contestant',
            constraint=models.UniqueConstraint(fields=('contest', 'name'), name='unique_contest_contestant'),
        ),
    ]
