# Generated by Django 5.2.8 on 2025-12-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_question_text'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.CheckConstraint(condition=models.Q(('levels__gte', 1)), name='min_number_of_levels'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='one_correct_answer_per_question'),
        ),
    ]
