# Generated by Django 5.2.8 on 2025-12-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_contest_min_number_of_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_edited',
            field=models.DateTimeField(null=True),
        ),
    ]
