# Generated by Django 5.2.8 on 2025-12-18 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_alter_contestant_contest_alter_option_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestcontrol',
            name='contestant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizapp.contestant'),
        ),
    ]
