# Generated by Django 5.2.8 on 2025-12-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_contestcontrol_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestcontrol',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
