# Generated by Django 5.2.8 on 2025-12-18 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_contestcontrol_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestcontrol',
            name='contestant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizapp.contestant'),
        ),
        migrations.AlterField(
            model_name='contestcontrol',
            name='current_question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizapp.question'),
        ),
    ]
