# Generated by Django 5.2.8 on 2025-12-21 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0012_alter_contestcontrol_contestant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestcontrol',
            name='contest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='quizapp.contest'),
        ),
    ]
