# Generated by Django 5.2.8 on 2025-12-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0015_alter_probablewrongoption_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probablewrongoption',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='probable_options', to='quizapp.option'),
        ),
    ]
