# Generated by Django 5.2.8 on 2026-01-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0016_alter_probablewrongoption_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probablewrongoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probable_wrong_options', to='quizapp.question'),
        ),
    ]
